---
name: runtrending

on:
  push:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
    inputs:
      tags:
        description: test
        default: test
        required: true
jobs:
  execscript:
    name: Exec Trending Script
    runs-on: ubuntu-20.04
    container: golang:1.16.7-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run go code
        run: |
          go run .
        working-directory: trending
